OCAMLC = ocamlc
TARGET = main
SRC = $(wildcard *.ml)
OBJ = $(patsubst %.ml, %.cmo, $(SRC))

FLAG = -c

$(TARGET): $(OBJ)
	$(OCAML) -o $@ $^

%.cmi: %.mli
	$(OCAMLC) $(FLAG) $<

%.cmo: %.ml %.cmi
	$(OCAMLC) $(FLAG) $<

.PHONY: clean
clean: 
	rm -f *.cmi *.cmo $(TARGET)
